language: node_js
node_js:
  - "10"
  - "8"

script:
  - npm run build
deploy:
  provider: firebase
  token:
    secure: "LwVjf4QjvdXehonO5OFa7CShCNHXKlykPJ7xmecpEGW8o7KafjXUiDGBHKXJKOQ2005m706UVGavCd65ngBnXrs8kTpculH6ZuhTegkeGB0V2PUo4icHw+pLbZcZEpxt1wbK1x7sIiXyfaBtTO9vmC4kVa/EgRLZR0bsHLaT7FuwwQuZ5rVI0G02B1bqtrMg+leZ/NVovEM6LWH3eZPlp2TxpYSS2X5a9Px2nI58t4jyoN6+dWI0sxHkLfJDADK19KThTgx041R41k+061olRSKud3D9FH6EsFmqV8wTkVg44eeIgM76KjP6EmehuvFWzmiQZsZSANSI5DFp/xd7nsCL8dZ0EFMzvV4QSzBFCqHxtfuEJLVovoiF9EMoOobqWGnNjZnNI0YKHTp5ZJekXJSGsuzAHY/E6z8HiCwMchptnEx2L+spXHcN3tkXB6Hz6d3nWF/FmdwYy2nUNHH09sR7zfX/5fCvlDOBdPqxUL7q0gQKC3JMvXYiClIuSHu9BFM3oon2voO28NorgXM74bLfw/v3u0K1KM4TklTgNFeIJg52QV1Rm7USBLKLgiKVK6OGah4JRMBsVT7ALml52UAd1xX8tCKVIkR/CGUBEhkYkLQhIsx1W/S9MFBsNaiBl9RykPVoapBl0XhvZKDjG+pOKzEf+tCR2b27Bvu1a90="
  project: techradar
